version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node

  working_directory: ~/app





jobs:
  checkout:
    <<: *defaults

    steps:
      - restore_cache:
          name: Restore Repository Cache
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - repo-{{ .Branch }}
            - repo-master
            - repo-

      - checkout

      - save_cache:
          name: Save Repository Cache
          key: repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .

      - persist_to_workspace:
          root: .
          paths:
            - .

  install-dependencies:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - restore_cache:
          name: Restore Build Cache
          keys:
            - build-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - build-{{ .Branch }}
            - build-master
            - build-

      - run:
          name: Add Yarn Binary Folder To $PATH
          command: export PATH="$PATH:`yarn global bin`"

      - run:
          name: Build the Application
          command: yarn run build

      - save_cache:
          name: Save Build Cache
          key: build-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .next

      - persist_to_workspace:
          root: .
          paths:
            - .next

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Add Yarn Binary Folder To $PATH
          command: export PATH="$PATH:`yarn global bin`"

      - run:
          name: Run tests
          command: yarn test

  coverage:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Add Yarn Binary Folder To $PATH
          command: export PATH="$PATH:`yarn global bin`"

      - run:
          name: Generate and upload coverage report
          command: yarn test-coverage

  dev-deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - add_ssh_keys

      - run:
          name: Keyscan (HACK)
          command: ssh-keyscan -H $DEV_DEPLOY_HOST >> ~/.ssh/known_hosts

      - run:
          name: Deploy to dev server
          command: rsync -r --delete-after --quiet ~/app/ $DEV_DEPLOY_USER@$DEV_DEPLOY_HOST:$DEV_DEPLOY_FOLDER

  prod-deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - add_ssh_keys

      - run:
          name: Keyscan (HACK)
          command: ssh-keyscan -H $PROD_DEPLOY_HOST >> ~/.ssh/known_hosts

      - run:
          name: Deploy to dev server
          command: rsync -r --delete-after --quiet ~/app/ $PROD_DEPLOY_USER@$PROD_DEPLOY_HOST:$PROD_DEPLOY_FOLDER





workflows:
  version: 2

  main:
    jobs:
      - checkout
      - install-dependencies:
          requires:
            - checkout
      # - test:
      #     requires:
      #       - install-dependencies
      # - coverage:
      #     requires:
      #       - install-dependencies
      - build:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - master
                - develop
      - dev-deploy:
          requires:
            # - test
            - build
          filters:
            branches:
              only: develop
      - prod-deploy:
          requires:
            # - test
            - build
          filters:
            branches:
              only: master
